# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

jobs:
- job: MyJob
  displayName: My First Job
  steps:
  - script: echo My first job
- job: Second Job
  displayName: Another one
  steps:
  - script: echo A second job
